import type { Metadata } from "next";
import "@/styles/global.css";
import { ThemeProvider } from "@/context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className="background md:m mt-4 md:mt-0">{children}</body>
      </ThemeProvider>
    </html>
  );
}
